Repository Argia-Org/incodnito, pull requests merged in 2020-07, with the labels that each got.

#9 Add PR Flutter checks
  .github/workflows/flutter-tests.yml
Labels: Priority: Medium, Status: Review Needed, Type: Maintenance

#11 Add initial Profile page
  assets/images/dp.jpeg
  assets/images/posts.jpeg
  lib/ui/pages/profile.dart
  lib/ui/widgets/profileGridImg.dart
  lib/utils/uidata.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#12 login/reg: Improve page UI
  lib/ui/pages/loginReg.dart
  lib/ui/widgets/custtextfield.dart
  lib/ui/widgets/loginregWidget.dart
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#14 feed: Initial page implementation
  lib/services/.gitignore
  lib/services/story_view/controller/story_controller.dart
  lib/services/story_view/story_view.dart
  lib/services/story_view/utils.dart
  lib/services/story_view/widgets/story_image.dart
  lib/services/story_view/widgets/story_video.dart
  lib/services/story_view/widgets/story_view.dart
  lib/ui/pages/feed.dart
  lib/ui/widgets/postDetails.dart
  lib/ui/widgets/profilePicture.dart
  pubspec.lock
  pubspec.yaml
Labels: Priority: High, Status: Completed, Type: Enhancement

#15 profile: Implementing Sliver appbar and slivers
  lib/ui/pages/landing.dart
  lib/ui/pages/profile.dart
  lib/ui/widgets/appBar.dart
  lib/utils/uidata.dart
  test/widget_test.dart
Labels: Priority: High, Status: Accepted, Type: Enhancement

#16 FeedPage:Added Sliverappbar
  lib/ui/pages/feed.dart
Labels: Priority: High, Status: Completed, Type: Enhancement

#20 Redesigned profile page
  assets/images/bg.jpg
  lib/ui/pages/editprofile.dart
  lib/ui/pages/profile.dart
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#21 Backend implementation for auth
  lib/services/auth.dart
  lib/ui/pages/loginReg.dart
  lib/ui/widgets/LRButtons.dart
  lib/utils/serverdata.dart
  pubspec.lock
  pubspec.yaml
Labels: Priority: High, Status: Completed, Type: Enhancement

#23 login/reg: Add local DB to save token
  lib/services/auth.dart
  lib/services/localdb.dart
  lib/ui/pages/loginReg.dart
  lib/ui/widgets/LRButtons.dart
  pubspec.lock
  pubspec.yaml
Labels: Priority: Medium, Status: Review Needed, Type: Maintenance
